### ISSUE TITLE
XMLHttpRequest  error

### ISSUE THREAD

**Issue by facuquilmes123** [elevenvac/instagram-downloader#1]
Hi, thanks a lot for that proyect !!!

I have this issue al request profile at inspect element.

XHR no ha podido cargar: GET "https://www.instagram.com/web/search/topsearch/?context=user&count=10&query=instagram".

Access to XMLHttpRequest at 'https://www.instagram.com/instagram/?__a=1' from origin 'https://sorteadores.online' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by elevenvac** [comment]
Sorry, we couldn't figure source of error.
